# Generated by Django 5.1.5 on 2025-01-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("faculty", "Faculty"),
                            ("student", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
